replicaCount: 1
tolerations:
  - key: "CriticalAddonsOnly"
    operator: "Exists"
    effect: "NoSchedule"
image:
  repository: platformacr001.azurecr.io/app-user-service
  tag: v1
service:
  port: 8001